### ISSUE TITLE
TF pull_from_github should pull a compiled artifact

### ISSUE THREAD

**Issue by Igneous** [DeaSTL/flappybird-htmx#3]
https://github.com/DeaSTL/flappybird-htmx/blob/main/deployment%2Fpull_from_github.tpl#L11

imo you're better off doing a CI-style build in GitHub actions, then zipping it up as an artifact. At which point your deployment process is a wget && unzip followed by running a binary. The systems wouldn't need git or a go runtime at that point.

**Comment by DeaSTL** [comment]
Yep just containerized it and put it on docker hub, just barely fits on a t2.nano.
